# SPDX-License-Identifier: Apache-2.0

name: e2e Testing transformers (only 3_3)
on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '.github/workflows/est_e2e.*' # This workflow
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '.github/workflows/test_e2e.*' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test_e2e:
    name: "test-e2e: using ${{ matrix.python }} on ${{ matrix.platform }}"
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        python:
          - "3.10"
        platform:
          - "ubuntu-latest"

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # https://github.com/actions/checkout/issues/249
          fetch-depth: 0

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml

      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh>=1.2

      - name: "Run e2e tests transformers (only 3_3)"
        run: |
          tox -- -k "transformers and 3_3" tests
